// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRByqFDWIVdRJFDCYtZlszDHTtimgs8Rw',
    appId: '1:589197954033:web:fb44b6d13e25d2f2869250',
    messagingSenderId: '589197954033',
    projectId: 'check-f3754',
    authDomain: 'check-f3754.firebaseapp.com',
    storageBucket: 'check-f3754.appspot.com',
    measurementId: 'G-4J06W40TF1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjPZLQj8wqz-8GOg8bZAMJLrIXE0WcmNs',
    appId: '1:589197954033:android:57bad92a3a447c1e869250',
    messagingSenderId: '589197954033',
    projectId: 'check-f3754',
    storageBucket: 'check-f3754.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsmZSqHIbmlmAsT6vIgKMRQrfr6ZTs9IY',
    appId: '1:589197954033:ios:248691e2e55c39c0869250',
    messagingSenderId: '589197954033',
    projectId: 'check-f3754',
    storageBucket: 'check-f3754.appspot.com',
    iosBundleId: 'com.example.testing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsmZSqHIbmlmAsT6vIgKMRQrfr6ZTs9IY',
    appId: '1:589197954033:ios:248691e2e55c39c0869250',
    messagingSenderId: '589197954033',
    projectId: 'check-f3754',
    storageBucket: 'check-f3754.appspot.com',
    iosBundleId: 'com.example.testing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRByqFDWIVdRJFDCYtZlszDHTtimgs8Rw',
    appId: '1:589197954033:web:58a61f644f386bb8869250',
    messagingSenderId: '589197954033',
    projectId: 'check-f3754',
    authDomain: 'check-f3754.firebaseapp.com',
    storageBucket: 'check-f3754.appspot.com',
    measurementId: 'G-GMMCM19VE8',
  );
}
